# Generated by Django 4.1.7 on 2023-04-21 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarvelComics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comicName', models.CharField(max_length=255)),
                ('issueTitle', models.CharField(max_length=255)),
                ('dateOfPublication', models.CharField(max_length=255)),
                ('issueDescription', models.TextField()),
                ('writer', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('characterName', models.CharField(max_length=255)),
                ('characterAlignment', models.CharField(max_length=255)),
                ('characterGender', models.CharField(max_length=255)),
                ('characterRace', models.CharField(max_length=255)),
                ('issueImageName', models.ImageField(blank=True, null=True, upload_to='', verbose_name='issueImages/SpiderMan/')),
            ],
        ),
        migrations.CreateModel(
            name='ComicRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRatings', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comicID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender_system_django_app.marvelcomics')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
