# Generated by Django 4.1.7 on 2023-04-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueImageNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueImageName', models.ImageField(blank=True, null=True, upload_to='', verbose_name='issueImages/SpiderMan/')),
                ('comicID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender_system_django_app.marvelcomics')),
            ],
        ),
    ]
