services:
  digital-systems-project:
    image: digital-systems-project
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    ports:
      - "8000:8000"
    entrypoint: ["./digital-systems-project-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: digital-systems-project-mysql_db
    environment:
      MYSQL_DATABASE: digital-systems-project-db
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin0209
    ports:
    - '3308:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/mysql/db:/var/lib/mysql